#
# CONFIGURATION FILE FOR THE SCRIPTS
#

# File/directory paths
paths:

  # File containing the list of URLs
  urls: urls/all-articles.txt

  # Directory for the downloaded pages
  downloads: downloads

  # Locations for the parsed articles
  articles:
    # File for the parsed articles (just title and text)
    text: all-articles-text.md

    # File for the parsed pages (everything)
    data: all-articles-data.yaml

authors:  
  # Authors to remove from the authors list
  # Note that it will always leave one author in there
  remove:
  - There is no such thing as ‘transracial’
  - On genderless passports
  - Special to National Post
  - National Post
  - NP View
  - Blog Nuggets
  - Robyn Urback on Avery Edison
  - Todd